---
title: "Topic Model Evaluation"
author: "Andreas Blätte (andreas.blaette@uni-due.de)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: topicmodelling.bibtex
vignette: >
  %\VignetteIndexEntry{Topic Model Evaluation}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

## Load libraries

```{r, eval = TRUE}
library(biglda)
library(polmineR)
library(parallel)
library(purrr)
library(stringi)
library(ggplot2)

use("RcppCWB", corpus = "REUTERS")
```


## Settings

```{r, eval = TRUE}
if (!mallet_is_installed()) mallet_install()
cores_to_use <- detectCores() - 1L
```


## Prepare data

```{r make_instance_list, message = FALSE, eval = TRUE}
discard <- c(tm::stopwords("en"), capitalize(tm::stopwords("en")))

instance_list <- corpus("REUTERS") %>%
  split(s_attribute = "id") %>%
  get_token_stream(p_attribute = "word", subset = {!word %in% discard}) %>%
  lapply(tolower) %>%
  keep(function(x) length(x) >= 50L) %>% # drop short documents
  sapply(stri_c, collapse = "\n") %>%
  discard(function(x) nchar(x) == 0L) %>% # drop empty documents
  as.instance_list()
```


## Fit models

```{r fit_models, eval = TRUE, message = FALSE, fig.width = 10}
metrics <- lapply(
  seq(from = 5, to = 30, by = 5),
  function(k){
    message("... fitting model for k: ", k)
    BTM <- BigTopicModel(n_topics = k, alpha_sum = 5.1, beta = 0.1)
    BTM$addInstances(instance_list)
    BTM$setNumThreads(cores_to_use)
    BTM$setTopicDisplay(0L, 0L)
    BTM$logger$setLevel(rJava::J("java.util.logging.Level")$OFF)
    BTM$setNumIterations(1000L)
    BTM$estimate()
    lda <- as_LDA(BTM, verbose = FALSE)
    N <- BTM$getDocLengthCounts()
    data.frame(
      k = k,
      cao2009 = BigCao2009(X = B(lda)),
      arun2010 = BigArun2010(beta = B(lda), gamma = G(lda), doclengths = N),
      deveaud2014 = BigDeveaud2014(beta = B(lda))
    )
  }
)
metrics <- do.call(rbind, metrics)
```


## Plot metrics

```{r}
values <- data.frame(
  metrics["k"],
  apply(
    metrics[, c("cao2009", "arun2010", "deveaud2014")],
    2,
    function(column) 
      scales::rescale(column, to = c(0, 1), from = range(column, na.rm = TRUE))
  )
)

values <- reshape2::melt(values, id.vars = "k", na.rm = TRUE)

# separate max-arg & min-arg metrics
values$group <- values$variable %in% "deveaud2014"
values$group <- base::factor(
  values$group,
  levels = c(FALSE, TRUE),
  labels = c("minimize", "maximize")
)

p <- ggplot(values, aes_string(x = "k", y = "value", group = "variable")) + 
  geom_line() +
  geom_point(aes_string(shape = "variable"), size = 3) +
  guides(size = FALSE, shape = guide_legend(title = "metrics:")) +
  scale_x_continuous(breaks = values$k) +
  labs(x = "number of topics", y = NULL) +
  facet_grid(group ~ .) +
  theme_bw() %+replace% theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(colour = "grey70"),
    panel.grid.minor.x = element_blank(),
    legend.key = element_blank(),
    strip.text.y = element_text(angle = 90)
  )

g <- ggplotGrob(p)
g$layout[g$layout$name == "strip-right", c("l", "r")] <- 3
grid::grid.newpage()
grid::grid.draw(g)
```
