// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BigCao2009
double BigCao2009(const arma::mat& X);
RcppExport SEXP _biglda_BigCao2009(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(BigCao2009(X));
    return rcpp_result_gen;
END_RCPP
}
// BigArun2010
double BigArun2010(const arma::mat& beta, const arma::mat& gamma, arma::vec doclengths);
RcppExport SEXP _biglda_BigArun2010(SEXP betaSEXP, SEXP gammaSEXP, SEXP doclengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type doclengths(doclengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(BigArun2010(beta, gamma, doclengths));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biglda_BigCao2009", (DL_FUNC) &_biglda_BigCao2009, 1},
    {"_biglda_BigArun2010", (DL_FUNC) &_biglda_BigArun2010, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_biglda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
