# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RcppArmadillo implementation of topic model metrics
#' 
#' @param X The beta matrix of an LDA topic model.
#' @rdname rcppmetrics
BigCao2009 <- function(X) {
    .Call(`_biglda_BigCao2009`, X)
}

#' @param beta The beta matrix.
#' @param gamma The gamma matrix.
#' @param doclengths A `vector` with document lengths (number of tokens).
#' @rdname rcppmetrics
BigArun2010 <- function(beta, gamma, doclengths) {
    .Call(`_biglda_BigArun2010`, beta, gamma, doclengths)
}

#' @rdname rcppmetrics
BigDeveaud2014 <- function(beta) {
    .Call(`_biglda_BigDeveaud2014`, beta)
}

