# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Write input format for MALLET using RcppCWB 
#' 
#' MALLET and PartiallyCollapsedLDA use an input format with a line-wise corpus
#' format with one document per line, where each line contains a document ID,
#' a placeholder label, and the raw document text separated by tabs. This
#' function uses a fast Rcpp/RcppCWB implementation for decoding a CWB corpus
#' and writing it to the specified file.
#' 
#' @param corpus Length-one character vector with the ID of a CWB corpus.
#' @param p_attribute A p-attribute (positional attribute).
#' @param s_attribute The s-attribute delimiting documents.
#' @param registry Length-one character vector with the registry directory.
#' @param filename Name of output file.
#' @examples
#' library(biglda)
#' library(polmineR)
#' library(RcppCWB)
#' use("RcppCWB")
#' 
#'  fname <- tempfile(fileext = ".txt")
#'  size <- RcppCWB::attribute_size(
#'    corpus = "ALBB",
#'    attribute = "article_id",
#'    attribute_type = "s",
#'    registry = corpus_registry_dir("ALBB")
#' )
NULL

#' biglda::write_mallet_input(
#'   corpus = "ALBB",
#'   s_attribute = "article_id",
#'   p_attribute = "word",
#'   strucs = 0L:(size - 1L),
#'   registry = corpus_registry_dir("ALBB"),
#'   filename = fname
#' )
write_mallet_input <- function(corpus, p_attribute, s_attribute, strucs, registry, filename) {
    .Call(`_biglda_write_mallet_input`, corpus, p_attribute, s_attribute, strucs, registry, filename)
}

#' RcppArmadillo implementation of topic model metrics
#' 
#' @param X The beta matrix of an LDA topic model.
#' @rdname rcppmetrics
BigCao2009 <- function(X) {
    .Call(`_biglda_BigCao2009`, X)
}

#' @param beta The beta matrix.
#' @param gamma The gamma matrix.
#' @param doclengths A `vector` with document lengths (number of tokens).
#' @rdname rcppmetrics
BigArun2010 <- function(beta, gamma, doclengths) {
    .Call(`_biglda_BigArun2010`, beta, gamma, doclengths)
}

#' @rdname rcppmetrics
#' @references \url{https://dn.revuesonline.com/gratuit/DN17_1_06_Deveau.pdf}
BigDeveaud2014 <- function(beta) {
    .Call(`_biglda_BigDeveaud2014`, beta)
}

