# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp/RcppCWB implementation for writing token stream
#' 
#' @param corpus corpus.
#' @param p_attribute X
#' @param s_attribute X
#' @param registry X
#' @param attribute_type X
#' @param filename X
#' @rdname rcppmetrics
write_token_stream <- function(corpus, p_attribute, s_attribute, registry, attribute_type, filename) {
    .Call(`_biglda_write_token_stream`, corpus, p_attribute, s_attribute, registry, attribute_type, filename)
}

#' Rcpp/RcppCWB implementation for writing token stream
#' 
#' @param corpus corpus.
#' @param p_attribute X
#' @param s_attribute X
#' @param registry X
#' @param attribute_type X
#' @param filename X
#' @rdname rcppmetrics
write_token_stream2 <- function(corpus, p_attribute, s_attribute, strucs, registry, attribute_type, filename) {
    .Call(`_biglda_write_token_stream2`, corpus, p_attribute, s_attribute, strucs, registry, attribute_type, filename)
}

#' RcppArmadillo implementation of topic model metrics
#' 
#' @param X The beta matrix of an LDA topic model.
#' @rdname rcppmetrics
BigCao2009 <- function(X) {
    .Call(`_biglda_BigCao2009`, X)
}

#' @param beta The beta matrix.
#' @param gamma The gamma matrix.
#' @param doclengths A `vector` with document lengths (number of tokens).
#' @rdname rcppmetrics
BigArun2010 <- function(beta, gamma, doclengths) {
    .Call(`_biglda_BigArun2010`, beta, gamma, doclengths)
}

#' @rdname rcppmetrics
#' @references \url{https://dn.revuesonline.com/gratuit/DN17_1_06_Deveau.pdf}
BigDeveaud2014 <- function(beta) {
    .Call(`_biglda_BigDeveaud2014`, beta)
}

